### ISSUE TITLE
Evaluate ND4BB technical report

### ISSUE THREAD

**Issue by mcourtot** [FAIRplus/FAIRPlus_squad2#14]
@mko sent early on: https://drive.google.com/open?id=1dudvrG-dtfwm0fseQ1HAFwSMujSuSwLD

@oyadenizbeyan did some evaluation of the workflows, @mkoatwork would like to know if the process he followed is a good start or not.
Specific interest in identifiers
Question about what is metadata - "provenance" vs metadata about the data which is inside the dataset, eg identifiers, column names etc

**Comment by FuqiX** [comment]
[ND4BB recipe v2](https://docs.google.com/document/d/1bftHuhVw9bndkJntHM5issDeFjkANEo0tM-eQPA5qBU/edit# ), based on Manfred's original report. 

**Changes:**
- some figures modified
- the structure of recipe adjusted to fit the recipe template and upload to the Cookbook page.
- removed some notes/comments generated during the FAIRification
- Some parts rephrased

V2 was also added to the FAIR cookbook page. https://fairplus.github.io/the-fair-cookbook/recipes/nd4bb_raw/FAIRification_CookBook_Recipe1_V02.html
