### ISSUE TITLE
Short README for KNIME workflow

### ISSUE THREAD

**Issue by mcourtot** [FAIRplus/FAIRPlus_squad2#35]
@mkoatwork  to write short readme on how to run the tool for ontology annotation against BioPortal and Zooma for the transcriptomics RESOLUTE dataset.

@ulo and @mcourtot to run locally and then we'll evaluate results.

**Comment by FuqiX** [comment]
The knime workflow described every step very clearly and showed how to carry out each step in great detail. However, I wasn't able to rerun the workflow file on my local machine because of dependency and version issues.
The ticket is closed because it's no longer active.
