### ISSUE TITLE
Overview examples RDA indicators RESOLUTE

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/FAIRPlus_squad2#41]
Tidy up remarks and comments from RESOLUTE assessment using the RDA indicators.

**Comment by FuqiX** [comment]
The tidy RESOLUTE assessment is [here](https://fairplus.github.io/fairification-results/2019-12-17-RESOLUTE-Pre-assessment/) 

Oya and Nick made a [summary](https://docs.google.com/presentation/d/1_QVIo0xbnYSZ9nRSjBLixGa8HNgS14anODAL0DYFJ_s/edit?usp=sharing) of remarks and comments from RESOLUTE, eTOX and ND4BB assessments, and provided the feedback to RDA.
