### ISSUE TITLE
Evaluate fairification level of ND4BB AMR dataset

### ISSUE THREAD

**Issue by mcourtot** [FAIRplus/FAIRPlus_squad2#5]
We need to have a starting point for assessing progress during this squad sprint

**Comment by FuqiX** [comment]
Pre-FAIRification assessed against RDA indicator v3 by Manfred, Fuqi and Oya https://fairplus.github.io/fairification-results/2019-12-17-ND4BB-post-assessment/
The FAIRification practice wasn't reflected in the pre- and post- FAIRification. The post-FAIRification results were the same as the pre ones.
