### ISSUE TITLE
Maintainance data type specific metadata templates

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/FAIRPlus_squad2#76]
Device general strategy for how to maintain a data type specific metadata templates, using the experiences gathered for #75 for transcriptomics data.

**Comment by nsjuty** [comment]
Jolanda to check assignee

**Comment by JolandaS** [comment]
As we are closing up on this use case, I would suggest to add this as a placeholder in the cookbook. It fits in with the idea to have more general recipes on handling metadata (templates) e.g. how to set up a template for other data types (than transcriptomics).
See [this issue](https://github.com/FAIRplus/the-fair-cookbook/issues/56) in the cookbook repo.
