### ISSUE TITLE
Latest version IMI catalogue project metadata template

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/FAIRPlus_squad2#78]
EBiSC data currently only in the current, public version of the IMI catalogue. Import into new version. Ask Wei for the latest version IMI catalogue project metadata template

**Comment by JolandaS** [comment]
Fuqi contacted Wei. Latest version received. Not final version (still in progress).
@FuqiX Where would be a good place for us to store that document with the template?

**Comment by FuqiX** [comment]
I've uploaded the file to the FAIR+ Gdrive https://drive.google.com/file/d/1qAYKWFQOPo85JIfgQO7jiZvkaBYkKBv9/view?usp=sharing Please note this template is still under development, new fields may be added (but won’t expect large changes of existing fields).

**Comment by FuqiX** [comment]
Template idntified
