### ISSUE TITLE
Recipe UC9.5

### ISSUE THREAD

**Issue by JolandaS** [FAIRplus/FAIRPlus_squad2#80]
BioSolr integration into catalogue for search/query extension

**Comment by JolandaS** [comment]
- [x] check compatibility latest BioSolr version with Solr version of catalogue

**Comment by daniwelter** [comment]
As it currently stands, BioSolr is not compatible with the data catalogue out of the box. I have not assessed exactly how much work would be required to update it to the latest version of Solr but this is definitely a non-trivial task (ie not just increment version numbers in config) as there are non-backwards compatible changes between Solr versions 5 and 8. I would estimate that at least 1.5-2 weeks of developer time would be required to perform this migration.

**Comment by JolandaS** [comment]
Out of scope for now
